TREE_SPAWN_CHANGE = 10
MAX_ITERS = 0
HEIGHT = 20
WIDTH = 40

CONST_REPOPULATION_CHANCE: int = 1000
CONST_TREE_GROWTH_CHANCE: int = 10
CONST_TREE_DEATH_CHANCE: int = 200
CONST_BUSH_GROWTH_CHANCE: int = 8
CONST_BUSH_DEATH_CHANCE: int = 400
CONST_OBSTACLE_APPEAR_CHANCE: int = 1
CONST_OBSTACLE_DISAPPEAR_CHANCE: int = 100
CONST_FRUIT_APPEAR_CHANCE: int = 30
CONST_FRUIT_TREE_PROXIMITY_APPEAR_CHANCE: int = 6000
CONST_FRUIT_DISAPPEAR_CHANCE: int = 10000
CONST_MEAT_DISAPPEAR_CHANCE: int = 1000

FILE_PATH = "D:\study\pioivis\sem4\lab1\save"
