# -*- coding: utf-8 -*-
from typing import NoReturn

# Author: Vodohleb04
# Form implementation generated from reading ui file 'intNumberParameterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mode import Mode

class Ui_intNumberParameterDialog(object):
    def setupUi(self, ui_dialog, intNumberParameterDialog, data_controller, icon_file, parameter_name: str, mode: Mode):
        self._min_value: int = 0
        self._max_value: int = 0
        self._mode = mode
        intNumberParameterDialog.setObjectName("intNumberParameterDialog")
        intNumberParameterDialog.resize(434, 112)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(icon_file), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        intNumberParameterDialog.setWindowIcon(icon)
        intNumberParameterDialog.setStyleSheet("background-color: rgb(255, 225, 230);")
        self.buttonBox = QtWidgets.QDialogButtonBox(intNumberParameterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(250, 70, 171, 32))
        self.buttonBox.setStyleSheet("background-color: rgb(199, 214, 255);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.maximalValueSpinBox = QtWidgets.QSpinBox(intNumberParameterDialog)
        self.maximalValueSpinBox.setGeometry(QtCore.QRect(230, 10, 191, 32))
        self.maximalValueSpinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.maximalValueSpinBox.setStyleSheet("background-color: rgb(199, 214, 255);")
        self.maximalValueSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.maximalValueSpinBox.setAccelerated(True)
        self.maximalValueSpinBox.setMaximum(1000000000)
        self.maximalValueSpinBox.setMinimum(1)
        self.maximalValueSpinBox.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.maximalValueSpinBox.setObjectName("maximalValueSpinBox")
        self.minimalValueSpinBox = QtWidgets.QSpinBox(intNumberParameterDialog)
        self.minimalValueSpinBox.setGeometry(QtCore.QRect(10, 10, 191, 32))
        self.minimalValueSpinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.minimalValueSpinBox.setStyleSheet("background-color: rgb(199, 214, 255);")
        self.minimalValueSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.minimalValueSpinBox.setAccelerated(True)
        self.minimalValueSpinBox.setMinimum(1)
        self.minimalValueSpinBox.setMaximum(1000000000)
        self.minimalValueSpinBox.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.minimalValueSpinBox.setObjectName("minimalValueSpinBox")
        self.line = QtWidgets.QFrame(intNumberParameterDialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 441, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(intNumberParameterDialog, parameter_name)
        self.buttonBox.accepted.connect(intNumberParameterDialog.accept)
        self.buttonBox.rejected.connect(intNumberParameterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(intNumberParameterDialog)

        self.minimalValueSpinBox.editingFinished.connect(lambda: self._minimal_value_changed())
        self.maximalValueSpinBox.editingFinished.connect(lambda: self._maximal_value_changed())
        self.connect_accepted(ui_dialog, intNumberParameterDialog, data_controller, parameter_name)

    def retranslateUi(self, intNumberParameterDialog, parameter_name: str):
        _translate = QtCore.QCoreApplication.translate
        intNumberParameterDialog.setWindowTitle(_translate("intNumberParameterDialog", f"Ввод параметра \""
                                                                                       f"{parameter_name}\""))
        self.maximalValueSpinBox.setSpecialValueText(_translate("intNumberParameterDialog", "Верхняя граница поиска"))
        self.minimalValueSpinBox.setSpecialValueText(_translate("intNumberParameterDialog", "Нижняя граница поиска"))

    def _minimal_value_changed(self) -> NoReturn:
        self._min_value = self.minimalValueSpinBox.value()
        if self._min_value > self._max_value:
            self._max_value = self._min_value
            self.maximalValueSpinBox.setValue(self._max_value)

    def _maximal_value_changed(self) -> NoReturn:
        self._max_value = self.maximalValueSpinBox.value()
        if self._max_value < self._min_value:
            self._min_value = self._max_value
            self.minimalValueSpinBox.setValue(self._min_value)

    def connect_accepted(self, ui_dialog, intNumberParameterDialog, data_controller, parameter) -> NoReturn:
        if self._mode == Mode.SEARCH_MODE:
            intNumberParameterDialog.accepted.connect(lambda: data_controller.int_number_param_complete_search(
                ui_dialog, parameter, self._min_value, self._max_value))
        elif self._mode == Mode.REMOVE_MODE:
            intNumberParameterDialog.accepted.connect(lambda: self._remove_agreement(ui_dialog,
                                                                                     intNumberParameterDialog,
                                                                                     data_controller,
                                                                                     parameter))

    def _remove_agreement(self, ui_dialog, intNumberParameterDialog, data_controller, parameter) -> NoReturn:
        result = QtWidgets.QMessageBox.question(
            intNumberParameterDialog,
            "Подтвердите удаление",
            "Вы действительно хотите удалить данные из таблицы?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
            QtWidgets.QMessageBox.No)
        if result == QtWidgets.QMessageBox.Yes:
            data_controller.int_number_param_complete_remove(ui_dialog, parameter, self._min_value, self._max_value)


