# Vodohleb04
# -*- coding: utf-8 -*-
from typing import NoReturn

# Form implementation generated from reading ui file 'help_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from config_controller import ConfigController


class Ui_helpDialog(object):
    def setupUi(self, helpDialog, config: ConfigController):
        helpDialog.setObjectName("helpDialog")
        helpDialog.resize(581, 337)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons/bimer.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        helpDialog.setWindowIcon(icon)
        helpDialog.setStyleSheet("background-color: rgb(255, 225, 230);")
        helpDialog.setSizeGripEnabled(False)
        helpDialog.setModal(False)
        self.okButton = QtWidgets.QPushButton(helpDialog)
        self.okButton.setGeometry(QtCore.QRect(540, 210, 41, 34))
        self.okButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.okButton.setStyleSheet("background-color: rgb(199, 214, 255);")
        self.okButton.setObjectName("okButton")
        self.textArea = QtWidgets.QTextBrowser(helpDialog)
        self.textArea.setGeometry(QtCore.QRect(0, 0, 581, 211))
        self.textArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textArea.setObjectName("textArea")
        self.helpComboBox = QtWidgets.QComboBox(helpDialog)
        self.helpComboBox.setGeometry(QtCore.QRect(0, 210, 281, 32))
        self.helpComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.helpComboBox.setStyleSheet("background-color: rgb(199, 214, 255);")
        self.helpComboBox.setObjectName("helpComboBox")
        self.helpComboBox.addItem("")
        self.helpComboBox.addItem("")
        self.helpComboBox.addItem("")
        self.helpComboBox.addItem("")
        self.helpComboBox.addItem("")
        self.okButton.clicked.connect(helpDialog.accept)
        self.retranslateUi(helpDialog)
        QtCore.QMetaObject.connectSlotsByName(helpDialog)

        self.helpComboBox.currentIndexChanged.connect(lambda: self.connect_clicked_checkbox(config))

    def retranslateUi(self, helpDialog):
        _translate = QtCore.QCoreApplication.translate
        helpDialog.setWindowTitle(_translate("helpDialog", "Help dialog"))
        self.okButton.setText(_translate("helpDialog", "OK"))
        self.helpComboBox.setItemText(0, _translate("helpDialog", "Выберите, о чём бы вы хотели узнать?"))
        self.helpComboBox.setItemText(1, _translate("helpDialog", "Общие сведения"))
        self.helpComboBox.setItemText(2, _translate("helpDialog", "Виды кирпичей"))
        self.helpComboBox.setItemText(3, _translate("helpDialog", "Уровни"))
        self.helpComboBox.setItemText(4, _translate("helpDialog", "Ускорение"))

    def connect_clicked_checkbox(self, config: ConfigController) -> NoReturn:
        if self.helpComboBox.currentIndex() == 0:
            self.textArea.clear()
        elif self.helpComboBox.currentIndex() == 1:
            self.textArea.setText(config.help_messages["general_info"])
        elif self.helpComboBox.currentIndex() == 2:
            self.textArea.setText(config.help_messages["bricks_info"])
        elif self.helpComboBox.currentIndex() == 3:
            self.textArea.setText(config.help_messages["acceleration_info"])
        elif self.helpComboBox.currentIndex() == 4:
            self.textArea.setText(config.help_messages["levels_info"])
        else:
            raise ValueError("Unexpected index")


def make_help_dialog(config: ConfigController) -> NoReturn:
    import sys
    app = QtWidgets.QApplication(sys.argv)
    helpDialog = QtWidgets.QDialog()
    ui = Ui_helpDialog()
    ui.setupUi(helpDialog, config)
    helpDialog.show()
    sys.exit(app.exec_())
