# Generated by Django 4.2 on 2023-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0002_remove_course_students_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('AOIS', 'Aois'), ('MAOIS', 'Maois'), ('PPOIS', 'Ppois'), ('ECONOMY', 'Economy'), ('IGISIT', 'Igisit'), ('LOIS', 'Lois'), ('COURSEWORK', 'Coursework')], max_length=16),
        ),
    ]
